# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

if ENV['fields']
  Field.create([
                 { name: 'Aeronautical Engineer' },
                 { name: 'Air Conditioning & Refrigeration Specialist' },
                 { name: 'Architect' },
                 { name: 'Certified Mine Foreman' },
                 { name: 'Certified Plant Mechanic' },
                 { name: 'Certified Public Accountant' },
                 { name: 'Certified Quarry Foreman' },
                 { name: 'Chemical Engineer' },
                 { name: 'Chemical Technician' },
                 { name: 'Chemist' },
                 { name: 'Chinese Druggist' },
                 { name: 'Civil Engineer' },
                 { name: 'Criminologist' },
                 { name: 'Customs Broker' },
                 { name: 'Dental Hygienist' },
                 { name: 'Dentist' },
                 { name: 'Electronics and Communications Engineer' },
                 { name: 'Electronics Engineer' },
                 { name: 'Electronics Technician' },
                 { name: 'Environmental Planner' },
                 { name: 'Fisheries Technologist' },
                 { name: 'Forester' },
                 { name: 'Geodetic Engineer' },
                 { name: 'Geologic Aide' },
                 { name: 'Geologist' },
                 { name: 'Guidance Counselor' },
                 { name: 'HBRL' },
                 { name: 'Interior Designer' },
                 { name: 'Landscape Architect' },
                 { name: 'Librarian' },
                 { name: 'Major Patron' },
                 { name: 'Marine Desk Officer' },
                 { name: 'Master Plumber' },
                 { name: 'Mechanical Engineer' },
                 { name: 'Medical Laboratory Technician' },
                 { name: 'Medical Technologist' },
                 { name: 'Metallurgical Engineer' },
                 { name: 'Metallurgical Plant Foreman' },
                 { name: 'Midwife' },
                 { name: 'Midwife (RA 2382)' },
                 { name: 'Mining Engineer' },
                 { name: 'Minor Patron' },
                 { name: 'Motor Engineer' },
                 { name: 'Naval Architect and Marine Engineer' },
                 { name: 'Nurse' },
                 { name: 'Nutritionist Dietician' },
                 { name: 'Occupational Therapist' },
                 { name: 'Occupational Therapy Technician' },
                 { name: 'Ocular Pharmacologist' },
                 { name: 'Optometrist' },
                 { name: 'Patron' },
                 { name: 'Pharmacist' },
                 { name: 'Physical Therapist' },
                 { name: 'Physical Therapy Technician' },
                 { name: 'Physician' },
                 { name: 'Professional Agricultural Engineer' },
                 { name: 'Professional Electrical Engineer' },
                 { name: 'Professional Electronics Engineer' },
                 { name: 'Professional Mechanical Engineer' },
                 { name: 'Psychologist' },
                 { name: 'Psychometrician' },
                 { name: 'Radiologic Technologist' },
                 { name: 'Real Estate Appraiser' },
                 { name: 'Real Estate Broker' },
                 { name: 'Real Estate Consultant' },
                 { name: 'Registered Electrical Engineer' },
                 { name: 'Registered Master Electrician' },
                 { name: 'Respiratory Therapist' },
                 { name: 'Sanitary Engineer' },
                 { name: 'Social Worker' },
                 { name: 'Sugar Technologist' },
                 { name: 'Veterinarian' },
                 { name: 'X-ray Technologist' }
               ])
end
